services:
  application:
    build: .
    command: gunicorn ${FLASK_APP} -b 0.0.0.0:8000 -w 4 -t 9 --log-level INFO
    container_name: "Application"
    environment:
      DEBUG: "True"
      SECRET_KEY: "a1b2c3d4e5f6g7h8i9j10k11l12m13n14o15p16q"
      SQLALCHEMY_DATABASE_URI: "sqlite:///db.sqlite3"
    image: app:${TAG:-local}
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/home/app/app/logs
